// Pulls the chart blocks for each shadcn chart family from ui.shadcn.com: the
// block names from the docs page, then each block's source from the registry.
// Writes src/data/shadcn.ts. Needs the network. Run by hand: npm run shadcn.
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const FAMILIES = ["area", "bar", "line", "pie", "radar", "radial"];
const DOCS = "https://ui.shadcn.com/charts";
const REGISTRY = "https://ui.shadcn.com/r/styles/new-york-v4";

async function text(url) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${url} answered ${response.status}`);
  return response.text();
}

/** "Bar Chart - Horizontal" becomes "Horizontal"; a bare "Bar Chart" is the plain one. */
function titleOf(source, family) {
  const match = source.match(/<CardTitle>([^<]+)<\/CardTitle>/);
  const full = match ? match[1].trim() : "";
  const suffix = full.split(" - ")[1]?.trim();
  return suffix || (full ? "Default" : family);
}

const out = {};
for (const family of FAMILIES) {
  const page = await text(`${DOCS}/${family}`);
  const names = [...new Set(page.match(new RegExp(`chart-${family}-[a-z-]+`, "g")) ?? [])].filter(
    (name) => !name.endsWith("-"),
  );
  if (names.length === 0) throw new Error(`no blocks found for ${family}`);
  const blocks = [];
  for (const name of names) {
    const item = JSON.parse(await text(`${REGISTRY}/${name}.json`));
    const source = item.files?.[0]?.content;
    if (!source) throw new Error(`${name} has no source in the registry`);
    blocks.push({ name, title: titleOf(source, family), source });
  }
  // Two cards can share a title (radar's grid-circle and grid-circle-no-lines); the name tells them apart.
  for (const block of blocks) {
    if (blocks.some((other) => other !== block && other.title === block.title)) {
      block.title = block.name
        .replace(`chart-${family}-`, "")
        .split("-")
        .map((word) => word[0].toUpperCase() + word.slice(1))
        .join(" ");
    }
  }
  out[family] = blocks;
  console.log(`${family}: ${blocks.map((block) => block.title).join(", ")}`);
}

const date = new Date().toISOString().slice(0, 10);
const body = FAMILIES.map(
  (family) =>
    `  ${family}: [\n` +
    out[family]
      .map(
        (block) =>
          `    {\n      name: ${JSON.stringify(block.name)},\n      title: ${JSON.stringify(block.title)},\n      source: ${JSON.stringify(block.source)},\n    },\n`,
      )
      .join("") +
    `  ],\n`,
).join("");
writeFileSync(
  join(root, "src", "data", "shadcn.ts"),
  `// Generated by scripts/shadcn.mjs from ui.shadcn.com on ${date}. Do not edit by hand.\n` +
    `import type { ShadcnBlock, ShadcnFamily } from "../lib/catalogue";\n\n` +
    `export const SHADCN_BLOCKS: Record<ShadcnFamily, ShadcnBlock[]> = {\n${body}};\n`,
);
console.log(`wrote src/data/shadcn.ts`);
